# Generated by Django 3.2.14 on 2023-09-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='child',
        ),
        migrations.AddField(
            model_name='card',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='_card_card_child_+', to='card.Card'),
        ),
    ]
