# Generated by Django 3.2.14 on 2023-09-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20230920_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='child',
        ),
        migrations.AddField(
            model_name='card',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='card.card'),
        ),
    ]
