# Generated by Django 3.2.14 on 2023-09-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_rename_child_card_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='isGoods',
            field=models.BooleanField(default=True),
        ),
    ]
