# Generated by Django 3.2.14 on 2023-09-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_isgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='isGoods',
            field=models.BooleanField(default=False),
        ),
    ]
