# Generated by Django 3.2.14 on 2023-09-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20230906_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blocks', models.ManyToManyField(null=True, related_name='baseball_with_blocks', to='ticketing.Block')),
            ],
        ),
    ]
