# Generated by Django 3.2.14 on 2023-09-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_baseball'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseball',
            name='eng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
