# Generated by Django 3.2.14 on 2023-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20230907_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='grade',
            field=models.ManyToManyField(related_name='blocks_with_grade', to='ticketing.Grade'),
        ),
    ]
