# Generated by Django 3.2.14 on 2023-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='logicalSeatId',
            field=models.IntegerField(),
        ),
    ]
