# Generated by Django 3.2.14 on 2023-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_alter_seat_logicalseatid'),
    ]

    operations = [
        migrations.CreateModel(
            name='grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('seat', models.ManyToManyField(related_name='grids_with_seat', to='ticketing.Seat')),
            ],
        ),
    ]
