# Generated by Django 3.2.14 on 2023-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseball',
            name='imageUrlThumnail',
            field=models.ImageField(blank=True, null=True, upload_to='ticketing/baseball/images/'),
        ),
    ]
