# Generated by Django 3.2.14 on 2023-10-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_football'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=255)),
                ('coords', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItSeatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('rb', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItSeatTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItSeatRanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.CharField(max_length=255)),
                ('figure', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seatrange_with_figure', to='ticketing.itfigure')),
                ('seatDetail', models.ManyToManyField(null=True, related_name='seatrange_with_seatdetail', to='ticketing.ItSeatDetail')),
            ],
        ),
        migrations.AddField(
            model_name='itseatdetail',
            name='seatType',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seatdetail_with_seattype', to='ticketing.itseattypes'),
        ),
        migrations.CreateModel(
            name='ItEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('venueName', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('placeName', models.CharField(max_length=255)),
                ('seatRange', models.ManyToManyField(null=True, related_name='event_with_seatrange', to='ticketing.ItSeatRanges')),
                ('seatType', models.ManyToManyField(null=True, related_name='event_with_seattype', to='ticketing.ItSeatTypes')),
            ],
        ),
    ]
