# Generated by Django 3.2.14 on 2023-10-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_auto_20231010_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itseatdetail',
            old_name='col',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='itseatdetail',
            old_name='row',
            new_name='top',
        ),
    ]
