# Generated by Django 3.2.14 on 2023-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_auto_20231011_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='itseatdetail',
            name='seatInfo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
